Repository Heavy-Division/heavy-division-bot, pull requests merged in 2022-06, with the labels that each got.

#22 refactor: updated link for .help and fixed typo in .cm
  .github/CHANGELOG.md
  src/commands/support/contentmanager.ts
  src/commands/utils/help.ts
Labels: bug, documentation

#24 refactor: fixes to .version and download links channel constant added
  .github/CHANGELOG.md
  .github/COMMANDS.md
  src/commands/B78XH/version.ts
  src/constants.ts
Labels: documentation

#27 refactor: .irs.B78XH command refactoring, correcting false information
  .github/CHANGELOG.md
  .github/CONTRIBUTING.md
  src/commands/B78XH/irs.ts
Labels: bug, documentation

#28 chore: updated discord.js package to 13.8.1
  package-lock.json
  package.json
Labels: dependencies

#30 fix: eslint configuration and setup
  .eslintrc.json
  package-lock.json
  package.json
  src/commands/B78XH/airframe.ts
  src/commands/B78XH/experimental.ts
  src/commands/B78XH/irs.ts
  src/commands/B78XH/simbriefimport.ts
  src/commands/B78XH/takeoffPerf.ts
  src/commands/B78XH/version.ts
  src/commands/general/donatorwelcome.ts
  src/commands/general/metarhow.ts
  src/commands/general/missingfeature.ts
  src/commands/general/oceanfix.ts
  src/commands/general/when.ts
  src/commands/index.ts
  src/commands/memes/boing.ts
  src/commands/memes/coffee.ts
  src/commands/memes/comi.ts
  src/commands/memes/cowsay.ts
  src/commands/memes/default.ts
  src/commands/memes/merge.ts
  src/commands/memes/p3d.ts
  src/commands/memes/premium.ts
  src/commands/memes/wingflex.ts
  src/commands/moderation/ban.ts
  src/commands/moderation/faq.ts
  src/commands/moderation/roleassignment.ts
  src/commands/moderation/rules.ts
  src/commands/moderation/timeout.ts
  src/commands/moderation/unban.ts
  src/commands/moderation/untimeout.ts
  src/commands/moderation/welcome.ts
  src/commands/moderation/whois.ts
  src/commands/support/autothrottle.ts
  src/commands/support/cleaninstall.ts
  src/commands/support/conflicts.ts
  src/commands/support/contentmanager.ts
  src/commands/support/controls.ts
  src/commands/support/ctd.ts
  src/commands/support/deadzones.ts
  src/commands/support/directx12.ts
  src/commands/support/dlc.ts
  src/commands/support/hud.ts
  src/commands/support/lnav.ts
  src/commands/support/msfs.ts
  src/commands/support/simbriefReferenceError.ts
  src/commands/utils/avatar.ts
  src/commands/utils/help.ts
  src/commands/utils/membercount.ts
  src/commands/utils/metar.ts
  src/commands/utils/ping.ts
  src/commands/utils/roleinfo.ts
  src/commands/utils/station.ts
  src/commands/utils/timezone.ts
  src/handlers/ban.ts
  src/handlers/messagedelete.ts
  src/handlers/messageupdate.ts
  src/handlers/scamlog.ts
Labels: meta, dependencies
