Repository Heavy-Division/heavy-division-bot, pull requests merged in 2022-10, with the labels that each got.

#49 refactor: removed unnecessary async modifiers, cleanup of some command descript…
  .github/CHANGELOG.md
  .github/COMMANDS.md
  .github/CONTRIBUTING.md
  src/commands/B78XH/airframe.ts
  src/commands/B78XH/experimental.ts
  src/commands/B78XH/irs.ts
  src/commands/B78XH/simbriefimport.ts
  src/commands/B78XH/takeoffPerf.ts
  src/commands/B78XH/version.ts
  src/commands/general/donate.ts
  src/commands/general/donatorwelcome.ts
  src/commands/general/metarhow.ts
  src/commands/general/missingfeature.ts
  src/commands/general/oceanfix.ts
  src/commands/general/when.ts
  src/commands/index.ts
  src/commands/memes/addon.ts
  src/commands/memes/boing.ts
  src/commands/memes/coffee.ts
  src/commands/memes/comi.ts
  src/commands/memes/default.ts
  src/commands/memes/merge.ts
  src/commands/memes/p3d.ts
  src/commands/memes/premium.ts
  src/commands/memes/wingflex.ts
  src/commands/support/autothrottle.ts
  src/commands/support/cleaninstall.ts
  src/commands/support/conflicts.ts
  src/commands/support/contentmanager.ts
  src/commands/support/controls.ts
  src/commands/support/ctd.ts
  src/commands/support/deadzones.ts
  src/commands/support/directx12.ts
  src/commands/support/dlc.ts
  src/commands/support/hud.ts
  src/commands/support/lnav.ts
  src/commands/support/msfs.ts
  src/commands/support/simbriefReferenceError.ts
  src/commands/utils/avatar.ts
  src/commands/utils/help.ts
  src/commands/utils/timezone.ts
  src/commands/utils/tod.ts
Labels: documentation, fix

#50 docs: Fix command docs errors
  .github/CHANGELOG.md
  .github/COMMANDS.md
Labels: documentation, fix

#51 feat: added apu command
  src/commands/index.ts
  src/commands/support/apu.ts
Labels: enhancement

#53 fear: Error handling for process start
  .github/CHANGELOG.md
  src/index.ts
Labels: enhancement

#54 docs: added .env.example
  .env.example
  .github/CHANGELOG.md
Labels: documentation, meta
